# Generated by Django 5.1.1 on 2024-10-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='contact_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
