# Generated by Django 5.1.2 on 2024-11-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='created_at',
            field=models.IntegerField(default=1731131215.088221),
        ),
        migrations.AlterField(
            model_name='admin',
            name='updated_at',
            field=models.IntegerField(default=1731131215.088221),
        ),
        migrations.AlterField(
            model_name='alert',
            name='created_at',
            field=models.IntegerField(default=1731131215.089221),
        ),
        migrations.AlterField(
            model_name='alert',
            name='updated_at',
            field=models.IntegerField(default=1731131215.089221),
        ),
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.IntegerField(default=1731131215.089221),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.IntegerField(default=1731131215.089221),
        ),
        migrations.AlterField(
            model_name='resident',
            name='created_at',
            field=models.IntegerField(default=1731131215.088221),
        ),
        migrations.AlterField(
            model_name='resident',
            name='updated_at',
            field=models.IntegerField(default=1731131215.088221),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.IntegerField(default=1731131215.08722),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.IntegerField(default=1731131215.08722),
        ),
    ]
