# Generated by Django 5.1.1 on 2024-10-06 04:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_resident_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
