# Generated by Django 5.1.1 on 2024-10-06 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_resident_address_alter_resident_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='landmark',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resident',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
