# Generated by Django 5.1.1 on 2024-10-06 05:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_resident_address_alter_resident_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
