# Generated by Django 5.1.1 on 2024-10-06 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_resident_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
