# Generated by Django 5.1.2 on 2024-10-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_resident_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resident',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='resident',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
